# Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JAWS-UG北陸新幹線

event_label: イベント
shorten_url: https://bit.ly/jaws-ug-hokuriku-line

description: > # this means to ignore newlines until "baseurl:"
  北陸新幹線沿線のAWSのユーザーグループ勉強会、JAWS-UG北陸新幹線の告知＆記録サイト。

baseurl: "/jaws-ug-hokuriku-line" # the subpath of your site, e.g. /blog
url: "https://jaws-ug-kanazawa.github.io" # the base hostname & protocol for your site

#These settings might be able to go?
author: PharaohKJ
twitter_username: jawsug_kanazawa
github_username:  PharaohKJ
company_name: JAWS-UG Kanazawa

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html

destination: docs

include:
  - images